---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Security update:"
    labels:
      - "ok-to-test"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub workflows:"
    labels:
      - "ok-to-test"
    pull-request-branch-name:
      separator: "-"
